# Generated by Django 6.0.4 on 2026-05-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('restricoes', models.CharField(blank=True, help_text='Ex: glúten, lactose', max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponivel', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cardapio/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AGUARD_PAG', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto')], default='AGUARD_PAG', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cardapio.itemcardapio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Cardapio.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Cardapio.restaurante'),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Cardapio.restaurante'),
        ),
    ]
