# Generated by Django 6.0.4 on 2026-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pronto_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
